### ISSUE TITLE
Menu color grading breaks when entering inventory

### ISSUE THREAD

**Issue by Afbg123** [JamesWilko/GoonMod#100] opened 2015-09-15 07:01 UTC
Having any of the menu color grading presets enabled results in losing the color grading when entering your inventory, in both the lobby menu and main menu.

**Comment by JamesWilko** [comment] 2015-10-02 09:04
Can't reproduce using latest update with the new inventory. This may have happened using the old inventory though, so closing for now since it seems to be fixed with latest.

**Closed by JamesWilko** 2015-10-02 09:04 UTC
