### ISSUE TITLE
Push to interact broken

### ISSUE THREAD

**Issue by CharredFelix** [JamesWilko/GoonMod#67] opened 2015-04-01 20:56 UTC
No matter what setting I choose on the push to interact menu it will always remain on and the only way I can cancel is by pressing the interact button again.

**Comment by JamesWilko** [comment] 2015-04-12 12:18
This was caused by an error with the menu always defaulting toggle values to on, this should have been fixed in the latest patch.

**Closed by JamesWilko** 2015-04-12 12:18 UTC
